# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "うさぎ小屋"
email:
author: "Kimiyuki Onaka"
description:
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://kimiyuki.net"  # the base hostname & protocol for your site
exclude:
    -   "/.git"
    -   "/.github"
    -   "/README.md"
    -   "/main.py"

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
future: true
timezone: Asia/Tokyo

collections:
  writeups:
    output: true
    sort_by: title

plugins:
  # default on GitHub pages
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  # additional plugins
  - jekyll-redirect-from
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true
